name: Pull Requests Workflow

on:
  pull_request_target:
    types: [opened, reopened]

  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Author Assign
        if: github.event_name == 'pull_request_target'
        uses: toshimaru/auto-author-assign@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
